# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth_service.proto',
  package='authorization_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x61uth_service.proto\x12\x15\x61uthorization_service\"\x13\n\x02In\x12\r\n\x05value\x18\x01 \x01(\t\"\x14\n\x03Out\x12\r\n\x05value\x18\x01 \x01(\t2i\n\x14\x41uthorizationService\x12Q\n\x16ValidateOneLoginTokens\x12\x19.authorization_service.In\x1a\x1a.authorization_service.Out\"\x00\x62\x06proto3'
)




_IN = _descriptor.Descriptor(
  name='In',
  full_name='authorization_service.In',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='authorization_service.In.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=64,
)


_OUT = _descriptor.Descriptor(
  name='Out',
  full_name='authorization_service.Out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='authorization_service.Out.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['In'] = _IN
DESCRIPTOR.message_types_by_name['Out'] = _OUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

In = _reflection.GeneratedProtocolMessageType('In', (_message.Message,), {
  'DESCRIPTOR' : _IN,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:authorization_service.In)
  })
_sym_db.RegisterMessage(In)

Out = _reflection.GeneratedProtocolMessageType('Out', (_message.Message,), {
  'DESCRIPTOR' : _OUT,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:authorization_service.Out)
  })
_sym_db.RegisterMessage(Out)



_AUTHORIZATIONSERVICE = _descriptor.ServiceDescriptor(
  name='AuthorizationService',
  full_name='authorization_service.AuthorizationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=193,
  methods=[
  _descriptor.MethodDescriptor(
    name='ValidateOneLoginTokens',
    full_name='authorization_service.AuthorizationService.ValidateOneLoginTokens',
    index=0,
    containing_service=None,
    input_type=_IN,
    output_type=_OUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHORIZATIONSERVICE)

DESCRIPTOR.services_by_name['AuthorizationService'] = _AUTHORIZATIONSERVICE

# @@protoc_insertion_point(module_scope)
